name: vaultwarden
version: 1.33.0
summary: Unofficial Bitwarden compatible server written in Rust
description: |
  Vaultwarden is a Rust-based implementation of the Bitwarden® server API that provides
  compatibility with upstream Bitwarden® clients, perfect for self-hosted deployments
  where running the official resource-heavy service might not be ideal. Vaultwarden is neither
  associated with nor endorsed by Bitwarden® Inc.

base: core24
grade: stable
confinement: strict
license: AGPL-3.0-only
platforms:
  amd64:
  arm64:
  armhf:

layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libmariadb3:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libmariadb3

hooks:
  install:
    command-chain:
      - snap/command-chain/install.sh

environment:
  WEB_VAULT_FOLDER: $SNAP/web-vault
  DATA_FOLDER: $SNAP_DATA/data

apps:
  vaultwarden:
    command: bin/vaultwarden
    daemon: simple
    plugs: [network, network-bind]

parts:
  vaultwarden:
    plugin: nil
    build-packages:
      - wget
    override-build: |
      wget https://raw.githubusercontent.com/jjlin/docker-image-extract/main/docker-image-extract
      chmod +x docker-image-extract
      if [[ "$CRAFT_ARCH_BUILD_FOR" == "amd64" ]] ; then
        ./docker-image-extract vaultwarden/server:$SNAPCRAFT_PROJECT_VERSION
      elif [[ "$CRAFT_ARCH_BUILD_FOR" == "arm64" ]] ; then
        ./docker-image-extract -p linux/arm64 vaultwarden/server:$SNAPCRAFT_PROJECT_VERSION
      elif [[ "$CRAFT_ARCH_BUILD_FOR" == "armhf" ]] ; then
        ./docker-image-extract -p linux/arm/v7 vaultwarden/server:$SNAPCRAFT_PROJECT_VERSION
      fi
      mkdir $CRAFT_PART_INSTALL/bin/
      cp output/vaultwarden $CRAFT_PART_INSTALL/bin/
      cp -r output/web-vault/ $CRAFT_PART_INSTALL/
    stage-packages:
      - libmariadb3
      - libpq5
    stage:
      - bin/
      - usr/lib/
      - web-vault/
  local:
    plugin: dump
    source: snap/local
    source-type: local
