name: vaultwarden
version: 1.32.2
summary: Unofficial Bitwarden compatible server written in Rust
description: |
  Vaultwarden is a Rust-based implementation of the Bitwarden® server API that provides
  compatibility with upstream Bitwarden® clients, perfect for self-hosted deployments
  where running the official resource-heavy service might not be ideal. Vaultwarden is neither
  associated with nor endorsed by Bitwarden® Inc.

base: core24
grade: stable
confinement: strict
license: AGPL-3.0-only
platforms:
  amd64:
  arm64:
  armhf:

apps:
  vaultwarden:
    command: bin/vaultwarden
    daemon: simple
    plugs: [network, network-bind]

environment:
  WEB_VAULT_FOLDER: $SNAP/web-vault
  DATA_FOLDER: $SNAP_DATA/data

hooks:
  install:
    command-chain:
      - snap/command-chain/install.sh

layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libmariadb3:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libmariadb3

parts:
  vaultwarden:
    plugin: nil
    build-packages:
      - wget
    override-build: |
      wget https://raw.githubusercontent.com/jjlin/docker-image-extract/main/docker-image-extract
      chmod +x docker-image-extract
      if [[ "$CRAFT_ARCH_BUILD_FOR" == "amd64" ]] ; then
        ./docker-image-extract vaultwarden/server:$SNAPCRAFT_PROJECT_VERSION
      elif [[ "$CRAFT_ARCH_BUILD_FOR" == "arm64" ]] ; then
        ./docker-image-extract -p linux/arm64 vaultwarden/server:$SNAPCRAFT_PROJECT_VERSION
      elif [[ "$CRAFT_ARCH_BUILD_FOR" == "armhf" ]] ; then
        ./docker-image-extract -p linux/arm/v7 vaultwarden/server:$SNAPCRAFT_PROJECT_VERSION
      fi
    stage-packages:
      - "libmariadb3"
      - "libpq5"
    override-prime: |
      craftctl default
      mkdir -p bin/
      cp $CRAFT_PART_BUILD/output/vaultwarden bin/
      cp -r $CRAFT_PART_BUILD/output/web-vault ./
      rm -rf etc
      rm -rf usr/share
  local:
    after: [vaultwarden]
    plugin: dump
    source: snap/local
    source-type: local
