name: Build, test, and publish

on:
  workflow_dispatch:
  push:
    branches: [ "candidate" ]
    paths:
      - 'snap/**'

jobs:
  action:
    runs-on: ubuntu-22.04
    environment: candidate
    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: 'candidate'

    - name: Build
      run: |
        sudo sysctl -w net.ipv4.ip_forward=1
        sudo iptables -I DOCKER-USER -i lxdbr0 -j ACCEPT
        sudo iptables -I DOCKER-USER -o lxdbr0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
        sudo snap install snapcraft --classic
        sudo lxd init --minimal
        sudo snapcraft --build-for=amd64
        sudo snapcraft --build-for=arm64
        sudo snapcraft --build-for=armhf
        if ls *amd64.snap && ls *arm64.snap && ls *armhf.snap ; then
          echo BUILD_SUCCESS=yes >> "$GITHUB_ENV"
        fi

    - name: Test
      if: ${{ env.BUILD_SUCCESS == 'yes' }}
      run: |
        sudo snap install --dangerous *amd64.snap
        sleep 5
        if curl 127.0.0.1:8000 | grep -q 'Vaultwarden' ; then
          echo TEST_SUCCESS=yes >> "$GITHUB_ENV"
        else
          echo "Testing failed!"
          exit 1
        fi

    - name: Publish
      if: ${{ env.TEST_SUCCESS == 'yes' }}
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
      run: |
        snapcraft upload --release=candidate *amd64.snap
        snapcraft upload --release=candidate *arm64.snap
        snapcraft upload --release=candidate *armhf.snap
